//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Security.Cryptography;
using System.Text;

namespace EmployeeManagementApp.Models
{
    public partial class loginuser
    {
        public decimal id { get; set; }

        [DisplayName("ユーザ名")]
        public string name { get; set; }

        [DisplayName("パスワード")]
        [DataType(dataType: DataType.Password)]
        public string password { get; set; }

        public static string GeneratePasswordHash(string username, string password)
        {
            // ソルトを計算。
            var salt = new SHA256CryptoServiceProvider().ComputeHash(buffer: Encoding.UTF8.GetBytes($"secret_{username}"));

            // ソルトをパスワードに加えることでハッシュ化する文字列を長くし、同じハッシュ値が生成されないようにする。
            // ハッシュ関数を繰り返し適用することで、元の文字列を現実的な計算時間で求められなくする。
            var hash = new Rfc2898DeriveBytes(password, salt, iterations: 10000).GetBytes(cb: 32);

            return Convert.ToBase64String(hash);
        }
    }
}
